# <p style="text-align: center;"> Names </p>
## <p style="text-align: center;"> AI S1,S2 </p>
| <font size="4"> Name  </font> | <font size="4">  ID  </font>|
| --- | --- |
| <font size="4"> Ahmed Rushdi Mohammed </font> | <font size="4"> 20180008 </font>  |
|  <font size="4"> Mohammed Waleed Mohammed </font> | <font size="4"> 20180244 </font>  |
|  <font size="4"> Aoss Maged Sultan</font> | <font size="4"> 20180432 </font>  |

# Phase 1

### 1. Load Dataset

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
path = 'D:\\Study_code\\py\\ML\\phase1\\insurance.csv'
df = pd.read_csv(path)
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Phase 2
### Handle Empty cells

In [3]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

df contains no null values

### Encoding

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1, 4, 5])],
    remainder='passthrough'
)
X = ct.fit_transform(X)

One hot encode the data

### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
X = ss.fit_transform(X)

Data is scaled to Support SVR. And it won't affect any other model. 

### Train-test Split

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=0, shuffle=True)

# Phase 3
## Applying Models
### Multiple linear regression

In [8]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(X_train, y_train)
y_pred1 = model1.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred1.reshape(len(y_pred1), 1),
                      y_test.reshape(len(y_test), 1)), 1)[:10, :])

[[11039.18  9724.53]
 [ 9439.18  8547.69]
 [38719.18 45702.02]
 [16543.18 12950.07]
 [ 7263.18  9644.25]
 [ 3903.18  4500.34]
 [ 1471.18  2198.19]
 [14751.18 11436.74]
 [ 9407.18  7537.16]
 [ 7967.18  5425.02]]


### Polynomial regression

In [9]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree=2)
model2 = LinearRegression()
model2.fit(poly_reg.fit_transform(X_train), y_train)
y_pred2 = model2.predict(poly_reg.fit_transform(X_test))
print(np.concatenate((y_pred2.reshape(len(y_pred2), 1),
                      y_test.reshape(len(y_test), 1)), 1)[:10, :])

[[11440.    9724.53]
 [10272.    8547.69]
 [50320.   45702.02]
 [15152.   12950.07]
 [ 7888.    9644.25]
 [ 5104.    4500.34]
 [ 4528.    2198.19]
 [14672.   11436.74]
 [10576.    7537.16]
 [ 8624.    5425.02]]


### Decision Tree Regression

In [10]:
from sklearn.tree import DecisionTreeRegressor
model3 = DecisionTreeRegressor(random_state=0)
model3.fit(X_train, y_train)
y_pred3 = model3.predict(X_test)
print(np.concatenate((y_pred3.reshape(len(y_pred3), 1),
                      y_test.reshape(len(y_test), 1)), 1)[:10, :])

[[10065.41  9724.53]
 [ 8871.15  8547.69]
 [42983.46 45702.02]
 [13429.04 12950.07]
 [ 8688.86  9644.25]
 [21984.47  4500.34]
 [ 2196.47  2198.19]
 [10848.13 11436.74]
 [ 7209.49  7537.16]
 [ 4433.92  5425.02]]


### Random Forest Regression

In [11]:
from sklearn.ensemble import RandomForestRegressor
model4 = RandomForestRegressor(n_estimators=200, random_state=0)
model4.fit(X_train, y_train)
y_pred4 = model4.predict(X_test)
print(np.concatenate((y_pred4.reshape(len(y_pred4), 1),
                      y_test.reshape(len(y_test), 1)), 1)[:10, :])

[[10232.99  9724.53]
 [ 9179.99  8547.69]
 [44529.59 45702.02]
 [13098.93 12950.07]
 [ 9619.35  9644.25]
 [10534.18  4500.34]
 [ 2584.37  2198.19]
 [12278.62 11436.74]
 [ 7617.68  7537.16]
 [ 6205.27  5425.02]]


### Support Vector Regression

In [69]:
from sklearn.svm import SVR
ss_y = StandardScaler()
y_train_ss = ss_y.fit_transform(y_train.reshape(-1,1))
model5 = SVR(kernel='rbf',C=3)
model5.fit(X_train, y_train_ss.ravel())
y_pred5 = model5.predict(X_test)
y_pred5 = ss_y.inverse_transform(y_pred5)
print(np.concatenate((y_pred5.reshape(len(y_pred5), 1),
                      y_test.reshape(len(y_test), 1)), 1)[:10, :])

[[10898.64  9724.53]
 [ 9612.41  8547.69]
 [49310.4  45702.02]
 [13896.38 12950.07]
 [11285.48  9644.25]
 [ 5188.81  4500.34]
 [ 3283.71  2198.19]
 [12492.11 11436.74]
 [ 8485.79  7537.16]
 [ 6374.22  5425.02]]


## Evaluating Performance

In [70]:
from sklearn.metrics import r2_score
print("Multiple Linear Regression R squared:\t %1.5f"% (r2_score(y_test, y_pred1)))
print("Polynomial Regression R squared:\t %1.5f"% (r2_score(y_test, y_pred2)))
print("Decision Tree Regression R squared:\t %1.5f"% (r2_score(y_test, y_pred3)))
print("Random Forest Regression R squared:\t %1.5f"% (r2_score(y_test, y_pred4)))
print("Support Vector Regression R squared:\t %1.5f"% (r2_score(y_test, y_pred5)))

Multiple Linear Regression R squared:	 0.80009
Polynomial Regression R squared:	 0.88153
Decision Tree Regression R squared:	 0.71186
Random Forest Regression R squared:	 0.87896
Support Vector Regression R squared:	 0.89057


## Observations
1. The best performing model is SVR(rbf).
2. Within Expectations Random Forest performed better than the Decision Tree model.
3. Polynomial Regression (Second degree) performed better than Multiple Linear Regression. and the model becomes overfitted at higher degrees.